//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodExpress
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заказы
    {
        public int id { get; set; }
        public string Номер { get; set; }
        public string Дата { get; set; }
        public string Статус { get; set; }
        public string Наименование_товара { get; set; }
        public Nullable<int> Количество_товара { get; set; }
        public int Цена_товара { get; set; }
        public string Тип_строки { get; set; }
    
        public virtual Товары Товары { get; set; }
    }
}
